import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data', 'artists');
const OUT_FILE = path.join(ROOT, 'src', 'lib', 'albums.generated.ts');

const files = fs
  .readdirSync(DATA_DIR)
  .filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f))
  .sort();

const albums = files.map((file) => {
  const date = file.replace(/\.json$/, ''); // "YYYY-MM-DD"
  const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf-8'));
  if (!data.id) {
    throw new Error(`[generate-albums] ${file} is missing the "id" field`);
  }
  return { date, slug: data.id, data };
});

const out = `// AUTO-GENERATED by scripts/generate-albums.mjs — do not edit.
// Regenerated on each build via the "prebuild" npm script.

export type AlbumData = {
  id: string;
  [key: string]: unknown;
};

export type AlbumRecord = {
  date: string; // YYYY-MM-DD
  slug: string; // === data.id
  data: AlbumData;
};

export const ALBUMS: readonly AlbumRecord[] = ${JSON.stringify(albums, null, 2)} as const;

export const ALBUMS_BY_SLUG: Readonly<Record<string, AlbumRecord>> = Object.freeze(
  Object.fromEntries(ALBUMS.map((a) => [a.slug, a]))
);
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, out, 'utf-8');
console.log(`✓ Generated ${albums.length} albums → ${path.relative(ROOT, OUT_FILE)}`);
